### ISSUE TITLE
Bug reported in dinamic items

### ISSUE THREAD

**Issue by oscarsinuco** [reachtokish/rctx-contextmenu#21]
- `gatsby-remark-embedder` version: ?
- `node` version: v12.18.3
- `npm` (or `yarn`) version: npm 6.14.6

Relevant code or config

Failed to execute 'removeEventListener' on 'EventTarget': 2 arguments required, but only 1 present

What you did: I fixed this problem by adding a second parameter to the removeEventLister function like this: removeEventListener('resize', ()=>{}) but I'm not sure if this is the right thing I resolved

What happened: I'm using reactjs with class components, I'm adding dynamically several ContextMenuTrigger and ContextMenu with dynamic id's, when I add new ones to the state it works fine, but when I delete one and update the state the error occurs, I clarify that I'm using redux so what I do is delete it from the store and the store itself updates the state of the component

Reproduction repository: At this time I cannot

Problem description: I'm using reactjs with class components, I'm adding dynamically several ContextMenuTrigger and ContextMenu with dynamic id's, when I add new ones to the state it works fine, but when I delete one and update the state the error occurs, I clarify that I'm using redux so what I do is delete it from the store and the store itself updates the state of the component

Suggested solution: I fixed this problem by adding a second parameter to the removeEventLister function like this: removeEventListener('resize', ()=>{}) but I'm not sure if this is the right thing I resolved

**Comment by reachtokish** [comment]
Hi @oscarsinuco , thanks for raising the bug. Let me reproduce it at my end. But it's better if you can create sandbox and share that with me. It will be fixed as soon as possible.

**Comment by reachtokish** [comment]
Hey @oscarsinuco , this is resolved. Just released a version. Please update your local dependency for rctx-contextmenu to [1.3.3](https://www.npmjs.com/package/rctx-contextmenu/v/1.3.3) and it will be resolved.

You don't need to do any hack to dynamically add or remove menus. You can refer to this example https://github.com/reachtokish/rctx-contextmenu/blob/master/example/src/examples/example6.js

Thanks!

**Comment by reachtokish** [comment]
Closing this issue as it is fixed. Kindly open if the issue persists. Thnx
