### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by mapan1908** [reachtokish/rctx-contextmenu#30]
- `rctx-contextmenu` version:
- `node` version:
- `npm` (or `yarn`) version:

**Relevant code or config**

```javascript
```

**What you did:**

**What happened:**

**Reproduction repository:**

**Problem description:**

**Suggested solution:**

**Comment by reachtokish** [comment]
Added typescript support. Kindly update to latest version it will start effecting `index.d.ts` file. Thanks for reaching out.

Also, closing this issue, kindly reopen if you get any further issues.

Thanks,
