### ISSUE TITLE
Package's version on npmjs.com is newer than the version on github

### ISSUE THREAD

**Issue by MatriXiao88** [reachtokish/rctx-contextmenu#33]
- `rctx-contextmenu` version:
- `node` version:
- `npm` (or `yarn`) version:

**Relevant code or config**

```javascript
```

**What you did:**

**What happened:**

**Reproduction repository:**

**Problem description:**

**Suggested solution:**

Is there any code on local doesnt push to github?

**Comment by reachtokish** [comment]
Thanks for pointing it out. It shows correct version now
