### ISSUE TITLE
Type Issue for children props in index.d.ts

### ISSUE THREAD

**Issue by Crypto-zombie** [reachtokish/rctx-contextmenu#34]
- `rctx-contextmenu` version: 1.3.6
- `node` version: v16.17.0
- `npm` (or `yarn`) version: 8.15.0

**Relevant code or config**
    <div className="app">
      <ContextMenuTrigger
        id="my-context-menu-1"
      >
        <div className="box">
          Right Click On Me
        </div>
      </ContextMenuTrigger>

      <ContextMenu id="my-context-menu-1">
        <ContextMenuItem>Menu Item 1</ContextMenuItem>
        <ContextMenuItem>Menu Item 2</ContextMenuItem>
        <ContextMenuItem>Menu Item 3</ContextMenuItem>
        <ContextMenuItem>Menu Item 4</ContextMenuItem>
      </ContextMenu>
    </div>

**What you did:**
----------------------------------------------------------------------------------------------------------------------------------
  I just tried to run sample code on react-typescript project.
 
  "react": "^18.2.0",
  "typescript": "^4.7.4",
-------------------------------------------------------------------------------------------------------------------------------
**What happened:**
-------------------------------------------------------------------------------------------------------------------------------
Type '{ children: Element[]; id: string; appendTo: string; animation: string; }' is not assignable to type 'IntrinsicAttributes & ContextMenu'.
  Property 'children' does not exist on type 'IntrinsicAttributes & ContextMenu'.
    3 | const CustomContextMenu = () => {
    4 |   return (
  > 5 |       <ContextMenu 
      |        ^^^^^^^^^^^
------------------------------------------------------------------------------------------------------------------------------
**Problem description:**
-------------------------------------------------------------------------------------------------------------------------------
Type '{ children: Element[]; id: string; appendTo: string; animation: string; }' is not assignable to type 'IntrinsicAttributes & ContextMenu'.
-------------------------------------------------------------------------------------------------------------------------------

**Suggested solution:**
I solved this problem like this:
------------------------------------
rctx-contextmenu/src/index.d.ts

  export interface ContextMenu {
    id: string,
    appendTo?: string,
    animation?: string,
    hideOnLeave?: boolean,
    attributes?: object,
    className?: string,
    preventHideOnResize?: boolean,
    preventHideOnScroll?: boolean,
    onShow?: {(event: any): void},
    onHide?: {(event: any): void},
    children?: ReactNode, --------------------------------------->
    onMouseLeave?: {(event: any): void}
  }

  export interface ContextMenuItem {
    disabled?: boolean,
    preventClose?: boolean,
    disableWhileShiftPressed?: boolean,
    attributes?: object,
    className?: string,
    children?: ReactNode, ---------------------------------------->
    onClick?: {(event: any): void}
  }

  export interface ContextMenuTrigger {
    id: string,
    attributes?: object,
    disable?: boolean,
    className?: string,
    children?: ReactNode ------------------------------------------->
  }

  export interface Submenu {
    title: string,
    attributes?: object,
    className?: boolean,
    children?: ReactNode -------------------------------------------->
  }

I would like you to solve this issues as soon as possible.
Best Regards

Evgenii

**Comment by reachtokish** [comment]
Thanks for raising the issue.

This is resolved. Kindly use the latest version (1.4.1). Closing the ticket. Kindly open if it still exist
