### ISSUE TITLE
Support for strict mode

### ISSUE THREAD

**Issue by CodingDive** [reachtokish/rctx-contextmenu#35]
Thank you so much for this wonderful library! It's doing exactly what I was looking for.

- `rctx-contextmenu` version: "^1.3.7",
- `node` version: 18.8.0
- `npm` (or `yarn`) version: 1.22.19
- `react` version: 18.2.0

I just saw that it does not yet support StrictMode. I think the reason is the dependency `react-transition-group` that hasn't been updated since they removed their dependency on `findDomNode` which is the one throwing the error.

https://github.com/reactjs/react-transition-group/releases/tag/v4.4.0

**Comment by reachtokish** [comment]
Thanks for pointing it out. It is resolved. Kindly use latest version (1.4.1).

Closing the issue. Kindly open if it still exists.
