### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of t which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

### ISSUE THREAD

**Issue by zdwork** [reachtokish/rctx-contextmenu#38]
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of t which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

**Comment by reachtokish** [comment]
Thanks for creating the issue.

`rctx-contextmenu` uses `react-transition-group` for animations and what I found is that `react-transition-group` uses `object-assign` which uses `findDOMNode` internally. Which is causing the issue. For time being kindly remove `StrictMode` from your project to unblock yourself.

I will try to see an alternative of `react-transition-group`

**Comment by reachtokish** [comment]
This is resolved. Kindly use the latest version (1.4.1). Closing the ticket. Kindly open if it still exist
